name: Convert JSON to HTML Table

on:
  push:
    branches:
      - main  # Adjust this branch as needed

jobs:
  convert-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Convert JSON to HTML Table
        uses: Teebra/JSON-to-HTML-table@v2.0.0
        with:
          json-file: ./releases.json  # Specify the path to your JSON file
      - name: move file (bit of a hack)
        run: mv releases.html index.html
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
